apiVersion: v1
kind: Secret
metadata:
  name: sage-ui
  namespace: sage
type: Opaque
stringData:
    Globus_Auth_Client_ID: ""
    Globus_Auth_Client_Secret: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: sage-ui-mysql-env
  namespace: sage
type: Opaque
stringData:
    MYSQL_USER: ""
    MYSQL_PASSWORD: ""
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_DATABASE: ""
    MYSQL_HOST: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sage-ui-db
  namespace: sage
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sage-ui
  namespace: sage
spec:
  ports:
  - name: web
    port: 80
    targetPort: 80
  selector:
    k8s-app: sage-ui
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: sage
  labels:
    app: db
spec:
  selector:
    k8s-app: db
  type: ClusterIP
  ports:
  - name: db
    port: 3306
    protocol: TCP
    targetPort: 3306
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sage-ui
  namespace: sage
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: sage.nautilus.optiputer.net
    http:
      paths:
      - path: /
        backend:
          serviceName: sage-ui
          servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sage-ui
  namespace: sage
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: sage-ui
  template:
    metadata:
      labels:
        k8s-app: sage-ui
    spec:
      containers:
      - image: sagecontinuum/sage-ui:latest
        name: sage-ui
        command:
          - ash
          - -c
          - while [ $(nc -zv db 3306; echo $?) != 0 ] ; 
            do echo "wait..." ; sleep 2; done ; python manage.py migrate ; 
           python manage.py runserver 0.0.0.0:80
        env:
        - name: DEBUG_VALUE
          value: "TRUE"
        - name: Globus_Auth_Client_ID
          valueFrom:
            secretKeyRef:
                name: sage-ui
                key: Globus_Auth_Client_ID
        - name: Globus_Auth_Client_Secret
          valueFrom:
            secretKeyRef:
                name: sage-ui
                key: Globus_Auth_Client_Secret
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: sage-ui-mysql-env
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sage-ui-mysql-env
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sage-ui-mysql-env
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: sage-ui-mysql-env
              key: MYSQL_DATABASE
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: sage-ui-mysql-env
              key: MYSQL_HOST
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 4
            memory: 4Gi
          requests:
            memory: 2Gi
            cpu: 2
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: db
  name: db
  namespace: sage
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: db
    spec:
      containers:
      - image: mysql:8
        name: db
        resources:
          limits:
            cpu: 4
            memory: 4Gi
          requests:
            memory: 2Gi
            cpu: 2
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: sage-ui-db
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: sage-ui-mysql-env
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sage-ui-mysql-env
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sage-ui-mysql-env
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: sage-ui-mysql-env
              key: MYSQL_DATABASE
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: sage-ui-mysql-env
              key: MYSQL_HOST
        ports:
          - name: db
            containerPort: 3306
      restartPolicy: Always
      volumes:
      - name: sage-ui-db
        persistentVolumeClaim:
          claimName: sage-ui-db